#!/bin/ash
. /etc/default/lejos
echo "Please wait: booting..."
mknod /dev/tty1 c 4 1
setterm -cursor off > /dev/tty1
setterm -blank 0 > /dev/tty1
setterm -linewrap off > /dev/tty1
setterm -clear > /dev/tty1
cp ${LEJOS_HOME}/images/monobrick_logo.ev3i /dev/fb0
echo > /dev/tty1
echo > /dev/tty1
echo > /dev/tty1
echo > /dev/tty1
echo > /dev/tty1
echo > /dev/tty1
echo > /dev/tty1
ver=`cat /home/root/lejos/version`
ver=${ver:0:22}
echo $ver > /dev/tty1
echo -n "Starting..." > /dev/tty1
