#! /bin/sh
#echo "Start WiFi"
#/lejos/bin/startwlan
#echo "Mount dev system"
#busybox mount -t nfs -o nolock legovm:/export/Lego /legovm
# show lejos splash, while modules load
echo "Load modules"
/lejos/bin/init
echo "Load mono startup"
if [ ! -f "/usr/local/bin/StartupApp.exe.so" ]; then
  echo "AOT compiling startup app"
  /usr/local/bin/mono --aot=full /usr/local/bin/StartupApp.exe >> /var/log/startuplog 2>&1
  /usr/local/bin/mono --aot=full /usr/local/bin/MonoBrickFirmware.dll >> /var/log/startuplog 2>&1
fi
/usr/local/bin/mono --full-aot /usr/local/bin/StartupApp.exe >> /var/log/startuplog 2>&1  &
echo "Complete"

